loglevel: info
raftdir: data/
raftid: id1
raftaddr: localhost:40000
raftcluster: 
  - localhost:40000/id1
  - localhost:40001/id2
  - localhost:40002/id3
httpserveraddr: localhost:12345
respserveraddr: localhost:6379
walengine: alfheimdbwal

storeengine: badger