// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: badger_value.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BadgerStringValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     []byte `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	TimeStamp int64  `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Timeout   int64  `protobuf:"varint,3,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
}

func (x *BadgerStringValue) Reset() {
	*x = BadgerStringValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_badger_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BadgerStringValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadgerStringValue) ProtoMessage() {}

func (x *BadgerStringValue) ProtoReflect() protoreflect.Message {
	mi := &file_badger_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadgerStringValue.ProtoReflect.Descriptor instead.
func (*BadgerStringValue) Descriptor() ([]byte, []int) {
	return file_badger_value_proto_rawDescGZIP(), []int{0}
}

func (x *BadgerStringValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BadgerStringValue) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *BadgerStringValue) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

var File_badger_value_proto protoreflect.FileDescriptor

var file_badger_value_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x61, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x61, 0x0a, 0x11, 0x42, 0x61, 0x64, 0x67,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_badger_value_proto_rawDescOnce sync.Once
	file_badger_value_proto_rawDescData = file_badger_value_proto_rawDesc
)

func file_badger_value_proto_rawDescGZIP() []byte {
	file_badger_value_proto_rawDescOnce.Do(func() {
		file_badger_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_badger_value_proto_rawDescData)
	})
	return file_badger_value_proto_rawDescData
}

var file_badger_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_badger_value_proto_goTypes = []interface{}{
	(*BadgerStringValue)(nil), // 0: pb.BadgerStringValue
}
var file_badger_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_badger_value_proto_init() }
func file_badger_value_proto_init() {
	if File_badger_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_badger_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BadgerStringValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_badger_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_badger_value_proto_goTypes,
		DependencyIndexes: file_badger_value_proto_depIdxs,
		MessageInfos:      file_badger_value_proto_msgTypes,
	}.Build()
	File_badger_value_proto = out.File
	file_badger_value_proto_rawDesc = nil
	file_badger_value_proto_goTypes = nil
	file_badger_value_proto_depIdxs = nil
}
