// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: fsm_log.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FsmLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd       string   `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	CmdArgs   [][]byte `protobuf:"bytes,2,rep,name=CmdArgs,proto3" json:"CmdArgs,omitempty"`
	TimeStamp int64    `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *FsmLog) Reset() {
	*x = FsmLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fsm_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsmLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsmLog) ProtoMessage() {}

func (x *FsmLog) ProtoReflect() protoreflect.Message {
	mi := &file_fsm_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsmLog.ProtoReflect.Descriptor instead.
func (*FsmLog) Descriptor() ([]byte, []int) {
	return file_fsm_log_proto_rawDescGZIP(), []int{0}
}

func (x *FsmLog) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *FsmLog) GetCmdArgs() [][]byte {
	if x != nil {
		return x.CmdArgs
	}
	return nil
}

func (x *FsmLog) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_fsm_log_proto protoreflect.FileDescriptor

var file_fsm_log_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x73, 0x6d, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x52, 0x0a, 0x06, 0x46, 0x73, 0x6d, 0x4c, 0x6f, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x43, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x6d, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x41, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x07, 0x43, 0x6d, 0x64, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fsm_log_proto_rawDescOnce sync.Once
	file_fsm_log_proto_rawDescData = file_fsm_log_proto_rawDesc
)

func file_fsm_log_proto_rawDescGZIP() []byte {
	file_fsm_log_proto_rawDescOnce.Do(func() {
		file_fsm_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_fsm_log_proto_rawDescData)
	})
	return file_fsm_log_proto_rawDescData
}

var file_fsm_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fsm_log_proto_goTypes = []interface{}{
	(*FsmLog)(nil), // 0: pb.FsmLog
}
var file_fsm_log_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fsm_log_proto_init() }
func file_fsm_log_proto_init() {
	if File_fsm_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fsm_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsmLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fsm_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fsm_log_proto_goTypes,
		DependencyIndexes: file_fsm_log_proto_depIdxs,
		MessageInfos:      file_fsm_log_proto_msgTypes,
	}.Build()
	File_fsm_log_proto = out.File
	file_fsm_log_proto_rawDesc = nil
	file_fsm_log_proto_goTypes = nil
	file_fsm_log_proto_depIdxs = nil
}
